### ISSUE TITLE
"ImportError: cannot import name '_Union' from 'typing' " 

### ISSUE THREAD

**Issue by causey** [aws-samples/connected-drink-dispenser-workshop#2]
Thanks for your presentation today.  Probably more fun than I've had at a conference session.  I guess that reveals how little I get out.  :-)

Runing Python 3.8 on Mac and seeing this error after installing all the dependencies and trying to run `cdk synth`:

```
(awscli) 8c859026bc23:deploy causey$ cdk synth
Traceback (most recent call last):
  File "cdk_app.py", line 12, in <module>
    from aws_cdk import core
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 406, in <module>
    import jsii
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/_runtime.py", line 6, in <module>
    from jsii import _reference_map
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/_reference_map.py", line 6, in <module>
    from ._kernel.types import JSClass, Referenceable
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from jsii._kernel.providers import BaseProvider, ProcessProvider
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from jsii._kernel.providers.process import ProcessProvider
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 15, in <module>
    import cattr  # type: ignore
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/cattr/converters.py", line 3, in <module>
    from ._compat import (
  File "/Users/causey/.pyenv/versions/awscli/lib/python3.8/site-packages/cattr/_compat.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/Users/causey/.pyenv/versions/3.8.0/lib/python3.8/typing.py)
Subprocess exited with error 1
```

Any ideas?  Thanks!

**Comment by causey** [comment]
Oh, well it might be an upstream issue https://github.com/aws/jsii/issues/913

**Comment by gadams999** [comment]
Hi @causey , thanks for the details and we'll track. yes, for now this has been tested on  Python 3.7 and I've seen the same or similar issue with Python 3.8. I'll track the CDK issue and when see that closed test with 3.8.

Right now the workaround is to use 3.7. I'll put in a plug for my go to manager, [pyenv](https://github.com/pyenv/pyenv).

**Comment by gadams999** [comment]
Fix is in upstream of the jsii. Referenced [here](https://github.com/aws/aws-cdk/issues/4699)
